services:
  open-webui:
    build: .
    image: open-webui:local
    container_name: open-webui-standalone
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    env_file:
      - .env
    environment:
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # PostgreSQL Database Configuration
      - DATABASE_URL=${DATABASE_URL}

      # OAuth Configuration
      - ENABLE_OAUTH_SIGNUP=${ENABLE_OAUTH_SIGNUP}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME}
      - OAUTH_SCOPES=${OAUTH_SCOPES}
      - ENABLE_LOGIN_FORM=${ENABLE_LOGIN_FORM}
      - ENABLE_OLLAMA_API=false
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - VECTOR_DB=${VECTOR_DB}
      - PGVECTOR_DB_URL=${PGVECTOR_DB_URL}

      - MCP_ENABLE=true
              
    restart: unless-stopped
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  open-webui-data:
    driver: local
  postgres-data:
    driver: local